//burgerIngredientsAction
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_STATUS_OK = 'GET_INGREDIENTS_STATUS_OK';
export const GET_INGREDIENTS_STATUS_ERR = 'GET_INGREDIENTS_STATUS_ERR';